### ISSUE TITLE
Some mistakes

### ISSUE THREAD

**Issue by lipond** [douzi0248/Re-ID#1]
I have run the training and then run the test like this "python test.py", but it complains as following:

Traceback (most recent call last):
File "test.py", line 169, in <module>
gallery_feature = extract_feature(model,dataloaders['gallery'])
File "test.py", line 116, in extract_feature
ff = ff+f
RuntimeError: The size of tensor a (1536) must match the size of tensor b (2253) at non-singleton dimension 1

**Comment by douzi0248** [comment]
''return x16, x18,x22..........." change into ‘’return x15,x17,x21......................" in the model

**Comment by lipond** [comment]
> ''return x16, x18,x22..........." change into ‘’return x15,x17,x21......................" in the model

Thanks, it works!
