### ISSUE TITLE
MSMT17数据集精度

### ISSUE THREAD

**Issue by billtiger** [douzi0248/Re-ID#10]
请问您有没有试过同样的网络在MSMT17数据集上训练，在MSMT测试集上Rank1能达到多少？
我用您的网络在MSMT17上训练，batchsize=128，最终在MSMT测试集上Rank1只能达到55%，mAP只达到40%左右，相对于其他论文还存在明显差距，请问跟调参有很大的关系吗？ @douzi0248

**Comment by douzi0248** [comment]
没有试过，我只有一块卡，msmt17有点跑不动，batchsize等于128的话，学习率等参数都要重新调，不然准确率会下降。

---原始邮件---
发件人: "billtiger"<notifications@github.com&gt;
发送时间: 2020年1月2日(周四) 下午2:16
收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
抄送: "douzi"<740244859@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: [douzi0248/Re-ID] MSMT17数据集精度 (#10)



请问您有没有试过同样的网络在MSMT17数据集上训练，在MSMT测试集上Rank1能达到多少？
 我用您的网络在MSMT17上训练，batchsize=128，最终在MSMT测试集上Rank1只能达到55%，mAP只达到40%左右，相对于其他论文还存在明显差距，请问跟调参有很大的关系吗？ @douzi0248

**Comment by billtiger** [comment]
那以您的经验看，除了学习率还有哪些参数需要调整呢？

**Comment by douzi0248** [comment]
如果改变batchsize,batchsize=AXB，A和B是要调的，还有就是学习率什么下降以及学习率也要调。





---原始邮件---
发件人: "billtiger"<notifications@github.com&gt;
发送时间: 2020年1月2日(周四) 下午4:11
收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
抄送: "douzi"<740244859@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [douzi0248/Re-ID] MSMT17数据集精度 (#10)



那以您的经验看，除了学习率还有哪些参数需要调整呢？

**Comment by billtiger** [comment]
不好意思，pytorch新手，现在明白您的意思了，谢谢！
