### ISSUE TITLE
数据集设置问题 

### ISSUE THREAD

**Issue by Andrawzyf** [douzi0248/Re-ID#4]
up请教一下，我看你数据集的路径设置的是：data_dir = '/home/pt/下载/Market/pytorch' 然后是不是pytorch文件夹里面有train和val文件夹？我是这样设置的，但是跑出来好像出错了。。。 错误是RuntimeError: Found 0 files in subfolders of:

**Comment by douzi0248** [comment]
对有这两个文件夹，训练前你要先运行prepare.py那个文件



---原始邮件---
发件人: "Andraw"<notifications@github.com&gt;
发送时间: 2019年9月24日(星期二) 下午4:12
收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [douzi0248/Re-ID] 数据集设置问题  (#4)



up请教一下，我看你数据集的路径设置的是：data_dir = '/home/pt/下载/Market/pytorch' 然后是不是pytorch文件夹里面有train和val文件夹？我是这样设置的，但是跑出来好像出错了。。。 错误是RuntimeError: Found 0 files in subfolders of:

**Comment by Andrawzyf** [comment]
@douzi0248 这样子。。谢谢。。我试试。。

**Comment by Andrawzyf** [comment]
@douzi0248 这样子。。谢谢。。我试试。。
