### ISSUE TITLE
运行evaluate_gpu.py的问题

### ISSUE THREAD

**Issue by Andrawzyf** [douzi0248/Re-ID#5]
首先谢谢昨天的指点，已经可以运行了，但是请教一下运行evaluate_gpu.py测试rank准确度，需要准备什么文件么？我看好像要一个pytorch_result.mat这样的文件，这个是怎么生成的呢？

**Comment by douzi0248** [comment]
测试的时候要先运行test.py，测试的时候也要修改model里面的为return x15,x17,x21.....



---原始邮件---
发件人: "Andraw"<notifications@github.com&gt;
发送时间: 2019年9月25日(星期三) 上午8:42
收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [douzi0248/Re-ID] 运行evaluate_gpu.py的问题 (#5)



首先谢谢昨天的指点，已经可以运行了，但是请教一下运行evaluate_gpu.py测试rank准确度，需要准备什么文件么？我看好像要一个pytorch_result.mat这样的文件，这个是怎么生成的呢？

**Comment by Andrawzyf** [comment]
> 测试的时候要先运行test.py，测试的时候也要修改model里面的为return x15,x17,x21.....
> […](#)
> ---原始邮件--- 发件人: "Andraw"<notifications@github.com&gt; 发送时间: 2019年9月25日(星期三) 上午8:42 收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [douzi0248/Re-ID] 运行evaluate_gpu.py的问题 (#5) 首先谢谢昨天的指点，已经可以运行了，但是请教一下运行evaluate_gpu.py测试rank准确度，需要准备什么文件么？我看好像要一个pytorch_result.mat这样的文件，这个是怎么生成的呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

了解了，可以运行了，非常感谢！！！

**Comment by Andrawzyf** [comment]
可以运行了，非常感谢！！！
