### ISSUE TITLE
请问您的论文有发布在arxiv上吗？

### ISSUE THREAD

**Issue by xjhjinhui** [douzi0248/Re-ID#7]
如题
如果您已发布，可否发出链接参考一下呢？感谢

**Comment by douzi0248** [comment]
没有。



---原始邮件---
发件人: "Taylor King"<notifications@github.com&gt;
发送时间: 2019年12月27日(周五) 中午11:52
收件人: "douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [douzi0248/Re-ID] 请问您的论文有发布在arxiv上吗？ (#7)



如题
 如果您已发布，可否发出链接参考一下呢？感谢
