### ISSUE TITLE
about the r50_ibn_a.pth

### ISSUE THREAD

**Issue by billtiger** [douzi0248/Re-ID#9]
hello,where is the pretrained model "r50_ibn_a.pth"?

**Comment by douzi0248** [comment]
&nbsp;
  链接：https://pan.baidu.com/s/1lyfs6ALppBk37_phuQlLqA 
提取码：4s3b

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"billtiger"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月31日(星期二) 下午4:16
 收件人:&nbsp;"douzi0248/Re-ID"<Re-ID@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[douzi0248/Re-ID] about the r50_ibn_a.pth (#9)

 

 
hello,where is the pretrained model "r50_ibn_a.pth"?

**Comment by billtiger** [comment]
ok，thank you！best wishes to you~
